version: "3.8"
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=backend_nodejs_v2
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306
  backend:
    build:
      context: ../nodejs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=database-mysql
      - DB_PORT=3306
      # DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../reactjs/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p bookingcare up -d
